# Lab 2-1. Logistic Regression

*   Regression: input data $x$를 output data $y$로 매핑하는 모델 $f$를 찾는것.

*   Logistic Regression: 모델 $f$가 linear model의 output을 logistic function을 이용해서 0~1사이의 확률값을 예측함, 즉 $$f(\textbf{x})=\sigma(\textbf{w}^T\textbf{x}+b)=\dfrac{1}{1+e^{-(\textbf{w}^T\textbf{x}+b)}}$$

*   Loss function
$$\text{Loss}(\textbf{w})=-\dfrac{1}{N}\sum y\text{log}(f(\textbf{x}))+(1-y)\text{log}(1-f(\textbf{x})) $$   

*    Gradient Descent
$$\textbf{w}=\textbf{w}-\alpha \dfrac{\partial}{\partial\textbf{w}}\text{Loss}(\textbf{w})$$

#### Import torch

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F # 학습에 관련된 함수를 담고 있음
import torch.optim as optim # optimism에 관련된 모델. 경사하강법 등

### Logistic Regression with Toy Training Data

In [2]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]] #2차원 데이터
y_data = [[0], [0], [0], [1], [1], [1]] 

In [3]:
# 그대로 넣으면 int 텐서가 될텐데, 에러가 생길 수 있기 떄문에 float 텐서로 바꾼다.

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [4]:
print(x_train.shape)
print(y_train.shape) # target 

torch.Size([6, 2])
torch.Size([6, 1])


#### Compute the Hypothesis
$$f(\textbf{x})=\sigma(\textbf{w}^T\textbf{x}+b)=\dfrac{1}{1+e^{-(\textbf{w}^T\textbf{x}+b)}}$$


In [ ]:
print('e^1 equals: ', torch.exp(torch.FloatTensor([1])))

In [5]:
W = torch.zeros((2, 1), requires_grad=True) # 인풋이 2차원이였으니까
b = torch.zeros(1, requires_grad=True) # 아웃풋은 1차원""

# requires_grad = 경사하강법을 쓸 것이라면 True로 설정.

In [6]:
hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W) + b)))

In [7]:
print(hypothesis)
print(hypothesis.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])


`torch.sigmoid()` 함수를 쓸 수도 있음


In [8]:
print('1/(1+e^{-1}) equals: ', torch.sigmoid(torch.FloatTensor([1])))

1/(1+e^{-1}) equals:  tensor([0.7311])


In [9]:
hypothesis = torch.sigmoid(x_train.matmul(W) + b)

In [10]:
print(hypothesis)
print(hypothesis.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)
torch.Size([6, 1])


#### Computing the Loss Function (Low-level)

$$\text{Loss}(\textbf{w})=-\dfrac{1}{N}\sum y\text{log}(f(\textbf{x}))+(1-y)\text{log}(1-f(\textbf{x})) $$   

 `hypothesis` and `y_train` 사이의 차이를 측정하고 싶음.

 : hypothesis 는 예상한 값



In [11]:
print(hypothesis)
print(y_train)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


하나의 데이터에 대해서 다음과 같이 계산 가능

In [12]:
-(y_train[0] * torch.log(hypothesis[0]) + 
  (1 - y_train[0]) * torch.log(1 - hypothesis[0]))

tensor([0.6931], grad_fn=<NegBackward>)

전체 데이터에 대해서는 다음과 같이 간단하게 계산 가능

In [13]:
losses = -(y_train * torch.log(hypothesis) + 
           (1 - y_train) * torch.log(1 - hypothesis))
print(losses)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward>)


`.mean()` 을 사용하여 평균을 취함

In [14]:
cost = losses.mean()
print(cost)

tensor(0.6931, grad_fn=<MeanBackward0>)


#### Computing the Cost Function with `F.binary_cross_entropy`

실제로는 binary classification은 자주 쓰이기 때문에 pytorch에 `F.binary_cross_entropy` 라는 함수가 구현돼있음

(지난번 실습의 `torch.nn.MSELoss`처럼)

In [15]:
F.binary_cross_entropy(hypothesis, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)

#### Training with Low-level Binary Cross Entropy Loss

### 수기로 계산하는 버전

In [16]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [17]:
# 모델 초기화
W = torch.zeros((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b) # or .mm or @
    cost = -(y_train * torch.log(hypothesis) + 
             (1 - y_train) * torch.log(1 - hypothesis)).mean()

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.134722
Epoch  200/1000 Cost: 0.080643
Epoch  300/1000 Cost: 0.057900
Epoch  400/1000 Cost: 0.045300
Epoch  500/1000 Cost: 0.037261
Epoch  600/1000 Cost: 0.031673
Epoch  700/1000 Cost: 0.027556
Epoch  800/1000 Cost: 0.024394
Epoch  900/1000 Cost: 0.021888
Epoch 1000/1000 Cost: 0.019852


#### Training with `F.binary_cross_entropy`

### 내장함수 활용한 버전

In [18]:
# 모델 초기화
W = torch.zeros((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b) # or .mm or @
    cost = F.binary_cross_entropy(hypothesis, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.134722
Epoch  200/1000 Cost: 0.080643
Epoch  300/1000 Cost: 0.057900
Epoch  400/1000 Cost: 0.045300
Epoch  500/1000 Cost: 0.037261
Epoch  600/1000 Cost: 0.031672
Epoch  700/1000 Cost: 0.027556
Epoch  800/1000 Cost: 0.024394
Epoch  900/1000 Cost: 0.021888
Epoch 1000/1000 Cost: 0.019852


## Logistic Regression with Real Data

### Load File from Google Drive

In [22]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [60]:
diabetes = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/diabetes.csv')
print(diabetes.columns)
diabetes.head()

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')


Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [61]:
type(diabetes)

pandas.core.frame.DataFrame

In [62]:
print("dimension of diabetes data: {}".format(diabetes.shape))

dimension of diabetes data: (768, 9)


### Split and prepare the dataset

In [63]:
train = diabetes[:650]
test = diabetes[650:]

In [64]:
print(train.groupby('Outcome').size())

Outcome
0    427
1    223
dtype: int64


imbalanced dataset임을 확인 가능

In [65]:
x_train = np.asarray(train.drop('Outcome',1))
y_train = np.asarray(train['Outcome'])
x_test = np.asarray(test.drop('Outcome',1))
y_test = np.asarray(test['Outcome'])

input을 normalize 해준다.

In [66]:
means = np.mean(x_train, axis=0)
stds = np.std(x_train, axis=0)
x_train = (x_train - means)/stds
x_test = (x_test - means)/stds

In [67]:
x_train = torch.FloatTensor(x_train)
y_train = torch.FloatTensor(y_train).unsqueeze(-1) # 차원 하나 업그레이드 unsqueeze(-1) , tensor에 맞게 2차원으로 늘려줘야한다.
x_test = torch.FloatTensor(x_test)
y_test = torch.FloatTensor(y_test).unsqueeze(-1)

In [68]:
y_train.shape

torch.Size([650, 1])

### Training with F.binary_cross_entropy

In [69]:
# 모델 초기화
W = torch.zeros((8, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)

nb_epochs = 100
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b) # or .mm or @
    cost = F.binary_cross_entropy(hypothesis, y_train)

    # cost로 f(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 10번마다 로그 출력
    if epoch % 10 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/100 Cost: 0.693147
Epoch   10/100 Cost: 0.477473
Epoch   20/100 Cost: 0.468751
Epoch   30/100 Cost: 0.467308
Epoch   40/100 Cost: 0.467003
Epoch   50/100 Cost: 0.466932
Epoch   60/100 Cost: 0.466914
Epoch   70/100 Cost: 0.466910
Epoch   80/100 Cost: 0.466909
Epoch   90/100 Cost: 0.466908
Epoch  100/100 Cost: 0.466908


### Test Accuracy

In [57]:
W, b

(tensor([[ 0.4520],
         [ 1.0729],
         [-0.2492],
         [-0.0065],
         [-0.1097],
         [ 0.7790],
         [ 0.3553],
         [ 0.1201]], requires_grad=True),
 tensor([-0.9190], requires_grad=True))

In [70]:
hypothesis = torch.sigmoid(x_test.matmul(W) + b)
prediction = hypothesis >= torch.FloatTensor([0.5])
correct_prediction = prediction.float() == y_test
accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('The model has an accuracy of {:2.2f}% for the test set.'.format(accuracy * 100))

The model has an accuracy of 78.81% for the test set.


## (Optional) Balancing the training set

### 데이터 균형 맞추기

In [71]:
x_train = np.asarray(train.drop('Outcome',1))
y_train = np.asarray(train['Outcome'])
x_test = np.asarray(test.drop('Outcome',1))
y_test = np.asarray(test['Outcome'])
means = np.mean(x_train, axis=0)
stds = np.std(x_train, axis=0)
x_train = (x_train - means)/stds # 정규화 과정
x_test = (x_test - means)/stds

In [72]:
x_train_pos = x_train[y_train == 0] # 타겟 값이 0인 값
x_train_neg = x_train[y_train == 1] # 타겟 값이 1인 값
y_train_pos = y_train[y_train == 0]
y_train_neg = y_train[y_train == 1]

In [75]:
x_train_pos.shape, x_train_neg.shape

((427, 8), (427, 8))

In [74]:
ids = np.arange(len(x_train_neg))
choices = np.random.choice(ids, len(x_train_pos))
x_train_neg = x_train_neg[choices]
y_train_neg = y_train_neg[choices]

In [76]:
x_train = np.concatenate([x_train_pos, x_train_neg], axis=0)
y_train = np.concatenate([y_train_pos, y_train_neg], axis=0)

order = np.arange(len(x_train))
np.random.shuffle(order)
x_train = x_train[order]
y_train = y_train[order]

In [77]:
x_train = torch.FloatTensor(x_train)
y_train = torch.FloatTensor(y_train).unsqueeze(-1)
x_test = torch.FloatTensor(x_test)
y_test = torch.FloatTensor(y_test).unsqueeze(-1)

### Training with F.binary_cross_entropy

In [78]:
# 모델 초기화
W = torch.zeros((8, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1)

nb_epochs = 100
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b) # or .mm or @
    cost = F.binary_cross_entropy(hypothesis, y_train)

    # cost로 f(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 10번마다 로그 출력
    if epoch % 10 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/100 Cost: 0.693147
Epoch   10/100 Cost: 0.501940
Epoch   20/100 Cost: 0.495054
Epoch   30/100 Cost: 0.493911
Epoch   40/100 Cost: 0.493670
Epoch   50/100 Cost: 0.493614
Epoch   60/100 Cost: 0.493600
Epoch   70/100 Cost: 0.493596
Epoch   80/100 Cost: 0.493595
Epoch   90/100 Cost: 0.493595
Epoch  100/100 Cost: 0.493595


### Test Accuracy

In [79]:
hypothesis = torch.sigmoid(x_test.matmul(W) + b)
prediction = hypothesis >= torch.FloatTensor([0.5])
correct_prediction = prediction.float() == y_test
accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('The model has an accuracy of {:2.2f}% for the training set.'.format(accuracy * 100))

The model has an accuracy of 75.42% for the training set.


### 결과가 더 안 좋아졌다. 이 데이터는 데이터 밸런스가 별 영향이 없다는 뜻이다.